[package]
name = "nanoleaf-aurora"
version = "0.1.0"
authors = ["Shane Snover <ssnover95@gmail.com>"]
edition = "2018"

[lib]
name = "borealis"
path = "src/lib.rs"

[[bin]]
name = "nanoleaf-discovery"
path = "src/main.rs"

[dependencies]
reqwest = "0.10"
futures = "0.3"
futures-util = "0.3"
mdns = "1.1"
tokio = { version = "0.2.4", features = ["macros", "rt-core"]}